spring:
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080

wechat:
  mpAppId: wxd580c152c6800480
  mpAppSecret: 6e3dee15c819162b9cac23168b02ad94
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  scan: http://will.nat300.top
  websocket: ws://127.0.0.1:${server.port}/webSocket

